// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/chat/v1/chat.proto

package chatv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityEvent_Type int32

const (
	IdentityEvent_TYPE_UNSPECIFIED   IdentityEvent_Type = 0
	IdentityEvent_TYPE_EXPIRING_SOON IdentityEvent_Type = 1
	IdentityEvent_TYPE_EXPIRED       IdentityEvent_Type = 2
)

// Enum value maps for IdentityEvent_Type.
var (
	IdentityEvent_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_EXPIRING_SOON",
		2: "TYPE_EXPIRED",
	}
	IdentityEvent_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED":   0,
		"TYPE_EXPIRING_SOON": 1,
		"TYPE_EXPIRED":       2,
	}
)

func (x IdentityEvent_Type) Enum() *IdentityEvent_Type {
	p := new(IdentityEvent_Type)
	*p = x
	return p
}

func (x IdentityEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chat_v1_chat_proto_enumTypes[0].Descriptor()
}

func (IdentityEvent_Type) Type() protoreflect.EnumType {
	return &file_proto_chat_v1_chat_proto_enumTypes[0]
}

func (x IdentityEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityEvent_Type.Descriptor instead.
func (IdentityEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{15, 0}
}

type CreateChannelRequest_Type int32

const (
	CreateChannelRequest_TYPE_UNSPECIFIED CreateChannelRequest_Type = 0
	CreateChannelRequest_TYPE_DIRECT      CreateChannelRequest_Type = 1
	CreateChannelRequest_TYPE_GROUP       CreateChannelRequest_Type = 2
)

// Enum value maps for CreateChannelRequest_Type.
var (
	CreateChannelRequest_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_DIRECT",
		2: "TYPE_GROUP",
	}
	CreateChannelRequest_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_DIRECT":      1,
		"TYPE_GROUP":       2,
	}
)

func (x CreateChannelRequest_Type) Enum() *CreateChannelRequest_Type {
	p := new(CreateChannelRequest_Type)
	*p = x
	return p
}

func (x CreateChannelRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateChannelRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chat_v1_chat_proto_enumTypes[1].Descriptor()
}

func (CreateChannelRequest_Type) Type() protoreflect.EnumType {
	return &file_proto_chat_v1_chat_proto_enumTypes[1]
}

func (x CreateChannelRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateChannelRequest_Type.Descriptor instead.
func (CreateChannelRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{24, 0}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // User's public key for E2E encryption info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // e.g., image, video, voice, file
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *Media) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Media) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Media) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *UploadFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *UploadFileResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadFileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Certificate   []byte                 `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`                 // Issued client certificate
	PrivateKey    []byte                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"` // Issued client private key (if server generates it, which it does in our CA model)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *RegisterResponse) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

type GetChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeRequest) Reset() {
	*x = GetChallengeRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeRequest) ProtoMessage() {}

func (x *GetChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeRequest.ProtoReflect.Descriptor instead.
func (*GetChallengeRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{7}
}

func (x *GetChallengeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nonce         string                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChallengeResponse) Reset() {
	*x = GetChallengeResponse{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChallengeResponse) ProtoMessage() {}

func (x *GetChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChallengeResponse.ProtoReflect.Descriptor instead.
func (*GetChallengeResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{8}
}

func (x *GetChallengeResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetChallengeResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type RenewCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // Signature of the nonce
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertificateRequest) Reset() {
	*x = RenewCertificateRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertificateRequest) ProtoMessage() {}

func (x *RenewCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertificateRequest.ProtoReflect.Descriptor instead.
func (*RenewCertificateRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{9}
}

func (x *RenewCertificateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RenewCertificateRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RenewCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   []byte                 `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertificateResponse) Reset() {
	*x = RenewCertificateResponse{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertificateResponse) ProtoMessage() {}

func (x *RenewCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertificateResponse.ProtoReflect.Descriptor instead.
func (*RenewCertificateResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{10}
}

func (x *RenewCertificateResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Medias        []*Media               `protobuf:"bytes,3,rep,name=medias,proto3" json:"medias,omitempty"`
	ThreadId      string                 `protobuf:"bytes,4,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{11}
}

func (x *SendMessageRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetMedias() []*Media {
	if x != nil {
		return x.Medias
	}
	return nil
}

func (x *SendMessageRequest) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *SendMessageRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{12}
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type StreamMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamMessageRequest_SendMessage
	//	*StreamMessageRequest_Heartbeat
	Payload       isStreamMessageRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessageRequest) Reset() {
	*x = StreamMessageRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessageRequest) ProtoMessage() {}

func (x *StreamMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessageRequest.ProtoReflect.Descriptor instead.
func (*StreamMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{13}
}

func (x *StreamMessageRequest) GetPayload() isStreamMessageRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamMessageRequest) GetSendMessage() *SendMessageRequest {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessageRequest_SendMessage); ok {
			return x.SendMessage
		}
	}
	return nil
}

func (x *StreamMessageRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessageRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isStreamMessageRequest_Payload interface {
	isStreamMessageRequest_Payload()
}

type StreamMessageRequest_SendMessage struct {
	SendMessage *SendMessageRequest `protobuf:"bytes,1,opt,name=send_message,json=sendMessage,proto3,oneof"`
}

type StreamMessageRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*StreamMessageRequest_SendMessage) isStreamMessageRequest_Payload() {}

func (*StreamMessageRequest_Heartbeat) isStreamMessageRequest_Payload() {}

type StreamMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamMessageResponse_MessageReceived
	//	*StreamMessageResponse_PresenceEvent
	//	*StreamMessageResponse_ChannelJoined
	//	*StreamMessageResponse_ParticipantAdded
	//	*StreamMessageResponse_Error
	//	*StreamMessageResponse_IdentityEvent
	Payload       isStreamMessageResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessageResponse) Reset() {
	*x = StreamMessageResponse{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessageResponse) ProtoMessage() {}

func (x *StreamMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessageResponse.ProtoReflect.Descriptor instead.
func (*StreamMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{14}
}

func (x *StreamMessageResponse) GetPayload() isStreamMessageResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamMessageResponse) GetMessageReceived() *MessageReceived {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessageResponse_MessageReceived); ok {
			return x.MessageReceived
		}
	}
	return nil
}

func (x *StreamMessageResponse) GetPresenceEvent() *PresenceEvent {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessageResponse_PresenceEvent); ok {
			return x.PresenceEvent
		}
	}
	return nil
}

func (x *StreamMessageResponse) GetChannelJoined() *ChannelJoined {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessageResponse_ChannelJoined); ok {
			return x.ChannelJoined
		}
	}
	return nil
}

func (x *StreamMessageResponse) GetParticipantAdded() *ParticipantAdded {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessageResponse_ParticipantAdded); ok {
			return x.ParticipantAdded
		}
	}
	return nil
}

func (x *StreamMessageResponse) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessageResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *StreamMessageResponse) GetIdentityEvent() *IdentityEvent {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessageResponse_IdentityEvent); ok {
			return x.IdentityEvent
		}
	}
	return nil
}

type isStreamMessageResponse_Payload interface {
	isStreamMessageResponse_Payload()
}

type StreamMessageResponse_MessageReceived struct {
	MessageReceived *MessageReceived `protobuf:"bytes,1,opt,name=message_received,json=messageReceived,proto3,oneof"`
}

type StreamMessageResponse_PresenceEvent struct {
	PresenceEvent *PresenceEvent `protobuf:"bytes,2,opt,name=presence_event,json=presenceEvent,proto3,oneof"`
}

type StreamMessageResponse_ChannelJoined struct {
	ChannelJoined *ChannelJoined `protobuf:"bytes,3,opt,name=channel_joined,json=channelJoined,proto3,oneof"`
}

type StreamMessageResponse_ParticipantAdded struct {
	ParticipantAdded *ParticipantAdded `protobuf:"bytes,4,opt,name=participant_added,json=participantAdded,proto3,oneof"`
}

type StreamMessageResponse_Error struct {
	Error *ErrorEvent `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type StreamMessageResponse_IdentityEvent struct {
	IdentityEvent *IdentityEvent `protobuf:"bytes,6,opt,name=identity_event,json=identityEvent,proto3,oneof"`
}

func (*StreamMessageResponse_MessageReceived) isStreamMessageResponse_Payload() {}

func (*StreamMessageResponse_PresenceEvent) isStreamMessageResponse_Payload() {}

func (*StreamMessageResponse_ChannelJoined) isStreamMessageResponse_Payload() {}

func (*StreamMessageResponse_ParticipantAdded) isStreamMessageResponse_Payload() {}

func (*StreamMessageResponse_Error) isStreamMessageResponse_Payload() {}

func (*StreamMessageResponse_IdentityEvent) isStreamMessageResponse_Payload() {}

type IdentityEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          IdentityEvent_Type     `protobuf:"varint,1,opt,name=type,proto3,enum=chat.v1.IdentityEvent_Type" json:"type,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityEvent) Reset() {
	*x = IdentityEvent{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityEvent) ProtoMessage() {}

func (x *IdentityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityEvent.ProtoReflect.Descriptor instead.
func (*IdentityEvent) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{15}
}

func (x *IdentityEvent) GetType() IdentityEvent_Type {
	if x != nil {
		return x.Type
	}
	return IdentityEvent_TYPE_UNSPECIFIED
}

func (x *IdentityEvent) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ParticipantAdded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantAdded) Reset() {
	*x = ParticipantAdded{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantAdded) ProtoMessage() {}

func (x *ParticipantAdded) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantAdded.ProtoReflect.Descriptor instead.
func (*ParticipantAdded) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{16}
}

func (x *ParticipantAdded) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ParticipantAdded) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ParticipantAdded) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{17}
}

type MessageReceived struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChannelId      string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderUsername string                 `protobuf:"bytes,4,opt,name=sender_username,json=senderUsername,proto3" json:"sender_username,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Medias         []*Media               `protobuf:"bytes,6,rep,name=medias,proto3" json:"medias,omitempty"`
	ThreadId       string                 `protobuf:"bytes,7,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	ParentId       string                 `protobuf:"bytes,8,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageReceived) Reset() {
	*x = MessageReceived{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReceived) ProtoMessage() {}

func (x *MessageReceived) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReceived.ProtoReflect.Descriptor instead.
func (*MessageReceived) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{18}
}

func (x *MessageReceived) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageReceived) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *MessageReceived) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessageReceived) GetSenderUsername() string {
	if x != nil {
		return x.SenderUsername
	}
	return ""
}

func (x *MessageReceived) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageReceived) GetMedias() []*Media {
	if x != nil {
		return x.Medias
	}
	return nil
}

func (x *MessageReceived) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *MessageReceived) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *MessageReceived) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PresenceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Online        bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceEvent) Reset() {
	*x = PresenceEvent{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceEvent) ProtoMessage() {}

func (x *PresenceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceEvent.ProtoReflect.Descriptor instead.
func (*PresenceEvent) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{19}
}

func (x *PresenceEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PresenceEvent) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{20}
}

func (x *ErrorEvent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChannelJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelJoined) Reset() {
	*x = ChannelJoined{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelJoined) ProtoMessage() {}

func (x *ChannelJoined) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelJoined.ProtoReflect.Descriptor instead.
func (*ChannelJoined) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{21}
}

func (x *ChannelJoined) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelJoined) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceRequest) Reset() {
	*x = GetPresenceRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceRequest) ProtoMessage() {}

func (x *GetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{22}
}

func (x *GetPresenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPresenceRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceResponse) Reset() {
	*x = GetPresenceResponse{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceResponse) ProtoMessage() {}

func (x *GetPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceResponse.ProtoReflect.Descriptor instead.
func (*GetPresenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{23}
}

func (x *GetPresenceResponse) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *GetPresenceResponse) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type CreateChannelRequest struct {
	state                protoimpl.MessageState    `protogen:"open.v1"`
	Type                 CreateChannelRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=chat.v1.CreateChannelRequest_Type" json:"type,omitempty"`
	Participants         []string                  `protobuf:"bytes,2,rep,name=participants,proto3" json:"participants,omitempty"`
	ParticipantUsernames []string                  `protobuf:"bytes,3,rep,name=participant_usernames,json=participantUsernames,proto3" json:"participant_usernames,omitempty"`
	Name                 string                    `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateChannelRequest) Reset() {
	*x = CreateChannelRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelRequest) ProtoMessage() {}

func (x *CreateChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelRequest.ProtoReflect.Descriptor instead.
func (*CreateChannelRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{24}
}

func (x *CreateChannelRequest) GetType() CreateChannelRequest_Type {
	if x != nil {
		return x.Type
	}
	return CreateChannelRequest_TYPE_UNSPECIFIED
}

func (x *CreateChannelRequest) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *CreateChannelRequest) GetParticipantUsernames() []string {
	if x != nil {
		return x.ParticipantUsernames
	}
	return nil
}

func (x *CreateChannelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChannelResponse) Reset() {
	*x = CreateChannelResponse{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChannelResponse) ProtoMessage() {}

func (x *CreateChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChannelResponse.ProtoReflect.Descriptor instead.
func (*CreateChannelResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{25}
}

func (x *CreateChannelResponse) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type ListChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsRequest) Reset() {
	*x = ListChannelsRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsRequest) ProtoMessage() {}

func (x *ListChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsRequest.ProtoReflect.Descriptor instead.
func (*ListChannelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{26}
}

type ListChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*ChannelInfo         `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelsResponse) Reset() {
	*x = ListChannelsResponse{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelsResponse) ProtoMessage() {}

func (x *ListChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelsResponse.ProtoReflect.Descriptor instead.
func (*ListChannelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{27}
}

func (x *ListChannelsResponse) GetChannels() []*ChannelInfo {
	if x != nil {
		return x.Channels
	}
	return nil
}

type ChannelInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Participants         []string               `protobuf:"bytes,3,rep,name=participants,proto3" json:"participants,omitempty"`
	ParticipantUsernames []string               `protobuf:"bytes,4,rep,name=participant_usernames,json=participantUsernames,proto3" json:"participant_usernames,omitempty"`
	Name                 string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	LastReadId           string                 `protobuf:"bytes,6,opt,name=last_read_id,json=lastReadId,proto3" json:"last_read_id,omitempty"`
	LastMessageId        string                 `protobuf:"bytes,7,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"`
	UnreadCount          int32                  `protobuf:"varint,8,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ChannelInfo) Reset() {
	*x = ChannelInfo{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfo) ProtoMessage() {}

func (x *ChannelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfo.ProtoReflect.Descriptor instead.
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{28}
}

func (x *ChannelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChannelInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChannelInfo) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *ChannelInfo) GetParticipantUsernames() []string {
	if x != nil {
		return x.ParticipantUsernames
	}
	return nil
}

func (x *ChannelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelInfo) GetLastReadId() string {
	if x != nil {
		return x.LastReadId
	}
	return ""
}

func (x *ChannelInfo) GetLastMessageId() string {
	if x != nil {
		return x.LastMessageId
	}
	return ""
}

func (x *ChannelInfo) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type MarkAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsReadRequest) Reset() {
	*x = MarkAsReadRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadRequest) ProtoMessage() {}

func (x *MarkAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAsReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{29}
}

func (x *MarkAsReadRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *MarkAsReadRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	BeforeId      string                 `protobuf:"bytes,3,opt,name=before_id,json=beforeId,proto3" json:"before_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{30}
}

func (x *GetMessagesRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetMessagesRequest) GetBeforeId() string {
	if x != nil {
		return x.BeforeId
	}
	return ""
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*MessageReceived     `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{31}
}

func (x *GetMessagesResponse) GetMessages() []*MessageReceived {
	if x != nil {
		return x.Messages
	}
	return nil
}

type AddParticipantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Usernames     []string               `protobuf:"bytes,3,rep,name=usernames,proto3" json:"usernames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParticipantRequest) Reset() {
	*x = AddParticipantRequest{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParticipantRequest) ProtoMessage() {}

func (x *AddParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParticipantRequest.ProtoReflect.Descriptor instead.
func (*AddParticipantRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{32}
}

func (x *AddParticipantRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *AddParticipantRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *AddParticipantRequest) GetUsernames() []string {
	if x != nil {
		return x.Usernames
	}
	return nil
}

type AddParticipantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParticipantResponse) Reset() {
	*x = AddParticipantResponse{}
	mi := &file_proto_chat_v1_chat_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParticipantResponse) ProtoMessage() {}

func (x *AddParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_v1_chat_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParticipantResponse.ProtoReflect.Descriptor instead.
func (*AddParticipantResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_v1_chat_proto_rawDescGZIP(), []int{33}
}

func (x *AddParticipantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_chat_v1_chat_proto protoreflect.FileDescriptor

const file_proto_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x18proto/chat/v1/chat.proto\x12\achat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"L\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"A\n" +
	"\x05Media\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"f\n" +
	"\x11UploadFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\":\n" +
	"\x12UploadFileResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"n\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\vcertificate\x18\x02 \x01(\fR\vcertificate\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\fR\n" +
	"privateKey\"1\n" +
	"\x13GetChallengeRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"E\n" +
	"\x14GetChallengeResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\"P\n" +
	"\x17RenewCertificateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"<\n" +
	"\x18RenewCertificateResponse\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\"\xaf\x01\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12&\n" +
	"\x06medias\x18\x03 \x03(\v2\x0e.chat.v1.MediaR\x06medias\x12\x1b\n" +
	"\tthread_id\x18\x04 \x01(\tR\bthreadId\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\"4\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"\x97\x01\n" +
	"\x14StreamMessageRequest\x12@\n" +
	"\fsend_message\x18\x01 \x01(\v2\x1b.chat.v1.SendMessageRequestH\x00R\vsendMessage\x122\n" +
	"\theartbeat\x18\x02 \x01(\v2\x12.chat.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\xa3\x03\n" +
	"\x15StreamMessageResponse\x12E\n" +
	"\x10message_received\x18\x01 \x01(\v2\x18.chat.v1.MessageReceivedH\x00R\x0fmessageReceived\x12?\n" +
	"\x0epresence_event\x18\x02 \x01(\v2\x16.chat.v1.PresenceEventH\x00R\rpresenceEvent\x12?\n" +
	"\x0echannel_joined\x18\x03 \x01(\v2\x16.chat.v1.ChannelJoinedH\x00R\rchannelJoined\x12H\n" +
	"\x11participant_added\x18\x04 \x01(\v2\x19.chat.v1.ParticipantAddedH\x00R\x10participantAdded\x12+\n" +
	"\x05error\x18\x05 \x01(\v2\x13.chat.v1.ErrorEventH\x00R\x05error\x12?\n" +
	"\x0eidentity_event\x18\x06 \x01(\v2\x16.chat.v1.IdentityEventH\x00R\ridentityEventB\t\n" +
	"\apayload\"\xc3\x01\n" +
	"\rIdentityEvent\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.chat.v1.IdentityEvent.TypeR\x04type\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"F\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TYPE_EXPIRING_SOON\x10\x01\x12\x10\n" +
	"\fTYPE_EXPIRED\x10\x02\"f\n" +
	"\x10ParticipantAdded\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"\v\n" +
	"\tHeartbeat\"\xcc\x02\n" +
	"\x0fMessageReceived\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12'\n" +
	"\x0fsender_username\x18\x04 \x01(\tR\x0esenderUsername\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12&\n" +
	"\x06medias\x18\x06 \x03(\v2\x0e.chat.v1.MediaR\x06medias\x12\x1b\n" +
	"\tthread_id\x18\a \x01(\tR\bthreadId\x12\x1b\n" +
	"\tparent_id\x18\b \x01(\tR\bparentId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"@\n" +
	"\rPresenceEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\":\n" +
	"\n" +
	"ErrorEvent\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\rChannelJoined\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"I\n" +
	"\x12GetPresenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"f\n" +
	"\x13GetPresenceResponse\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\x127\n" +
	"\tlast_seen\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"\xfa\x01\n" +
	"\x14CreateChannelRequest\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".chat.v1.CreateChannelRequest.TypeR\x04type\x12\"\n" +
	"\fparticipants\x18\x02 \x03(\tR\fparticipants\x123\n" +
	"\x15participant_usernames\x18\x03 \x03(\tR\x14participantUsernames\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"=\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vTYPE_DIRECT\x10\x01\x12\x0e\n" +
	"\n" +
	"TYPE_GROUP\x10\x02\"6\n" +
	"\x15CreateChannelResponse\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"\x15\n" +
	"\x13ListChannelsRequest\"H\n" +
	"\x14ListChannelsResponse\x120\n" +
	"\bchannels\x18\x01 \x03(\v2\x14.chat.v1.ChannelInfoR\bchannels\"\x8b\x02\n" +
	"\vChannelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\"\n" +
	"\fparticipants\x18\x03 \x03(\tR\fparticipants\x123\n" +
	"\x15participant_usernames\x18\x04 \x03(\tR\x14participantUsernames\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\flast_read_id\x18\x06 \x01(\tR\n" +
	"lastReadId\x12&\n" +
	"\x0flast_message_id\x18\a \x01(\tR\rlastMessageId\x12!\n" +
	"\funread_count\x18\b \x01(\x05R\vunreadCount\"Q\n" +
	"\x11MarkAsReadRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\"f\n" +
	"\x12GetMessagesRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1b\n" +
	"\tbefore_id\x18\x03 \x01(\tR\bbeforeId\"K\n" +
	"\x13GetMessagesResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.chat.v1.MessageReceivedR\bmessages\"o\n" +
	"\x15AddParticipantRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\x12\x1c\n" +
	"\tusernames\x18\x03 \x03(\tR\tusernames\"2\n" +
	"\x16AddParticipantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf9\n" +
	"\n" +
	"\vChatService\x12\\\n" +
	"\vHealthCheck\x12\x1b.chat.v1.HealthCheckRequest\x1a\x1c.chat.v1.HealthCheckResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/health\x12X\n" +
	"\bRegister\x12\x18.chat.v1.RegisterRequest\x1a\x19.chat.v1.RegisterResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/register\x12j\n" +
	"\fGetChallenge\x12\x1c.chat.v1.GetChallengeRequest\x1a\x1d.chat.v1.GetChallengeResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/auth/challenge\x12r\n" +
	"\x10RenewCertificate\x12 .chat.v1.RenewCertificateRequest\x1a!.chat.v1.RenewCertificateResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/renew\x12w\n" +
	"\vSendMessage\x12\x1b.chat.v1.SendMessageRequest\x1a\x1c.chat.v1.SendMessageResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/channels/{channel_id}/messages\x12U\n" +
	"\x0eBidiStreamChat\x12\x1d.chat.v1.StreamMessageRequest\x1a\x1e.chat.v1.StreamMessageResponse\"\x00(\x010\x01\x12g\n" +
	"\rCreateChannel\x12\x1d.chat.v1.CreateChannelRequest\x1a\x1e.chat.v1.CreateChannelResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/channels\x12\x84\x01\n" +
	"\x0eAddParticipant\x12\x1e.chat.v1.AddParticipantRequest\x1a\x1f.chat.v1.AddParticipantResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/v1/channels/{channel_id}/participants\x12k\n" +
	"\n" +
	"MarkAsRead\x12\x1a.chat.v1.MarkAsReadRequest\x1a\x16.google.protobuf.Empty\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/channels/{channel_id}/read\x12\\\n" +
	"\n" +
	"UploadFile\x12\x1a.chat.v1.UploadFileRequest\x1a\x1b.chat.v1.UploadFileResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/upload\x12a\n" +
	"\fListChannels\x12\x1c.chat.v1.ListChannelsRequest\x1a\x1d.chat.v1.ListChannelsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/channels\x12t\n" +
	"\vGetMessages\x12\x1b.chat.v1.GetMessagesRequest\x1a\x1c.chat.v1.GetMessagesResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/channels/{channel_id}/messages\x12n\n" +
	"\vGetPresence\x12\x1b.chat.v1.GetPresenceRequest\x1a\x1c.chat.v1.GetPresenceResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/users/{user_id}/presenceB\x1eZ\x1cgo-simple-chat/api/v1;chatv1b\x06proto3"

var (
	file_proto_chat_v1_chat_proto_rawDescOnce sync.Once
	file_proto_chat_v1_chat_proto_rawDescData []byte
)

func file_proto_chat_v1_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_v1_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chat_v1_chat_proto_rawDesc), len(file_proto_chat_v1_chat_proto_rawDesc)))
	})
	return file_proto_chat_v1_chat_proto_rawDescData
}

var file_proto_chat_v1_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_chat_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_proto_chat_v1_chat_proto_goTypes = []any{
	(IdentityEvent_Type)(0),          // 0: chat.v1.IdentityEvent.Type
	(CreateChannelRequest_Type)(0),   // 1: chat.v1.CreateChannelRequest.Type
	(*HealthCheckRequest)(nil),       // 2: chat.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),      // 3: chat.v1.HealthCheckResponse
	(*RegisterRequest)(nil),          // 4: chat.v1.RegisterRequest
	(*Media)(nil),                    // 5: chat.v1.Media
	(*UploadFileRequest)(nil),        // 6: chat.v1.UploadFileRequest
	(*UploadFileResponse)(nil),       // 7: chat.v1.UploadFileResponse
	(*RegisterResponse)(nil),         // 8: chat.v1.RegisterResponse
	(*GetChallengeRequest)(nil),      // 9: chat.v1.GetChallengeRequest
	(*GetChallengeResponse)(nil),     // 10: chat.v1.GetChallengeResponse
	(*RenewCertificateRequest)(nil),  // 11: chat.v1.RenewCertificateRequest
	(*RenewCertificateResponse)(nil), // 12: chat.v1.RenewCertificateResponse
	(*SendMessageRequest)(nil),       // 13: chat.v1.SendMessageRequest
	(*SendMessageResponse)(nil),      // 14: chat.v1.SendMessageResponse
	(*StreamMessageRequest)(nil),     // 15: chat.v1.StreamMessageRequest
	(*StreamMessageResponse)(nil),    // 16: chat.v1.StreamMessageResponse
	(*IdentityEvent)(nil),            // 17: chat.v1.IdentityEvent
	(*ParticipantAdded)(nil),         // 18: chat.v1.ParticipantAdded
	(*Heartbeat)(nil),                // 19: chat.v1.Heartbeat
	(*MessageReceived)(nil),          // 20: chat.v1.MessageReceived
	(*PresenceEvent)(nil),            // 21: chat.v1.PresenceEvent
	(*ErrorEvent)(nil),               // 22: chat.v1.ErrorEvent
	(*ChannelJoined)(nil),            // 23: chat.v1.ChannelJoined
	(*GetPresenceRequest)(nil),       // 24: chat.v1.GetPresenceRequest
	(*GetPresenceResponse)(nil),      // 25: chat.v1.GetPresenceResponse
	(*CreateChannelRequest)(nil),     // 26: chat.v1.CreateChannelRequest
	(*CreateChannelResponse)(nil),    // 27: chat.v1.CreateChannelResponse
	(*ListChannelsRequest)(nil),      // 28: chat.v1.ListChannelsRequest
	(*ListChannelsResponse)(nil),     // 29: chat.v1.ListChannelsResponse
	(*ChannelInfo)(nil),              // 30: chat.v1.ChannelInfo
	(*MarkAsReadRequest)(nil),        // 31: chat.v1.MarkAsReadRequest
	(*GetMessagesRequest)(nil),       // 32: chat.v1.GetMessagesRequest
	(*GetMessagesResponse)(nil),      // 33: chat.v1.GetMessagesResponse
	(*AddParticipantRequest)(nil),    // 34: chat.v1.AddParticipantRequest
	(*AddParticipantResponse)(nil),   // 35: chat.v1.AddParticipantResponse
	(*timestamppb.Timestamp)(nil),    // 36: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 37: google.protobuf.Empty
}
var file_proto_chat_v1_chat_proto_depIdxs = []int32{
	5,  // 0: chat.v1.SendMessageRequest.medias:type_name -> chat.v1.Media
	13, // 1: chat.v1.StreamMessageRequest.send_message:type_name -> chat.v1.SendMessageRequest
	19, // 2: chat.v1.StreamMessageRequest.heartbeat:type_name -> chat.v1.Heartbeat
	20, // 3: chat.v1.StreamMessageResponse.message_received:type_name -> chat.v1.MessageReceived
	21, // 4: chat.v1.StreamMessageResponse.presence_event:type_name -> chat.v1.PresenceEvent
	23, // 5: chat.v1.StreamMessageResponse.channel_joined:type_name -> chat.v1.ChannelJoined
	18, // 6: chat.v1.StreamMessageResponse.participant_added:type_name -> chat.v1.ParticipantAdded
	22, // 7: chat.v1.StreamMessageResponse.error:type_name -> chat.v1.ErrorEvent
	17, // 8: chat.v1.StreamMessageResponse.identity_event:type_name -> chat.v1.IdentityEvent
	0,  // 9: chat.v1.IdentityEvent.type:type_name -> chat.v1.IdentityEvent.Type
	36, // 10: chat.v1.IdentityEvent.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 11: chat.v1.MessageReceived.medias:type_name -> chat.v1.Media
	36, // 12: chat.v1.MessageReceived.created_at:type_name -> google.protobuf.Timestamp
	36, // 13: chat.v1.GetPresenceResponse.last_seen:type_name -> google.protobuf.Timestamp
	1,  // 14: chat.v1.CreateChannelRequest.type:type_name -> chat.v1.CreateChannelRequest.Type
	30, // 15: chat.v1.ListChannelsResponse.channels:type_name -> chat.v1.ChannelInfo
	20, // 16: chat.v1.GetMessagesResponse.messages:type_name -> chat.v1.MessageReceived
	2,  // 17: chat.v1.ChatService.HealthCheck:input_type -> chat.v1.HealthCheckRequest
	4,  // 18: chat.v1.ChatService.Register:input_type -> chat.v1.RegisterRequest
	9,  // 19: chat.v1.ChatService.GetChallenge:input_type -> chat.v1.GetChallengeRequest
	11, // 20: chat.v1.ChatService.RenewCertificate:input_type -> chat.v1.RenewCertificateRequest
	13, // 21: chat.v1.ChatService.SendMessage:input_type -> chat.v1.SendMessageRequest
	15, // 22: chat.v1.ChatService.BidiStreamChat:input_type -> chat.v1.StreamMessageRequest
	26, // 23: chat.v1.ChatService.CreateChannel:input_type -> chat.v1.CreateChannelRequest
	34, // 24: chat.v1.ChatService.AddParticipant:input_type -> chat.v1.AddParticipantRequest
	31, // 25: chat.v1.ChatService.MarkAsRead:input_type -> chat.v1.MarkAsReadRequest
	6,  // 26: chat.v1.ChatService.UploadFile:input_type -> chat.v1.UploadFileRequest
	28, // 27: chat.v1.ChatService.ListChannels:input_type -> chat.v1.ListChannelsRequest
	32, // 28: chat.v1.ChatService.GetMessages:input_type -> chat.v1.GetMessagesRequest
	24, // 29: chat.v1.ChatService.GetPresence:input_type -> chat.v1.GetPresenceRequest
	3,  // 30: chat.v1.ChatService.HealthCheck:output_type -> chat.v1.HealthCheckResponse
	8,  // 31: chat.v1.ChatService.Register:output_type -> chat.v1.RegisterResponse
	10, // 32: chat.v1.ChatService.GetChallenge:output_type -> chat.v1.GetChallengeResponse
	12, // 33: chat.v1.ChatService.RenewCertificate:output_type -> chat.v1.RenewCertificateResponse
	14, // 34: chat.v1.ChatService.SendMessage:output_type -> chat.v1.SendMessageResponse
	16, // 35: chat.v1.ChatService.BidiStreamChat:output_type -> chat.v1.StreamMessageResponse
	27, // 36: chat.v1.ChatService.CreateChannel:output_type -> chat.v1.CreateChannelResponse
	35, // 37: chat.v1.ChatService.AddParticipant:output_type -> chat.v1.AddParticipantResponse
	37, // 38: chat.v1.ChatService.MarkAsRead:output_type -> google.protobuf.Empty
	7,  // 39: chat.v1.ChatService.UploadFile:output_type -> chat.v1.UploadFileResponse
	29, // 40: chat.v1.ChatService.ListChannels:output_type -> chat.v1.ListChannelsResponse
	33, // 41: chat.v1.ChatService.GetMessages:output_type -> chat.v1.GetMessagesResponse
	25, // 42: chat.v1.ChatService.GetPresence:output_type -> chat.v1.GetPresenceResponse
	30, // [30:43] is the sub-list for method output_type
	17, // [17:30] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_chat_v1_chat_proto_init() }
func file_proto_chat_v1_chat_proto_init() {
	if File_proto_chat_v1_chat_proto != nil {
		return
	}
	file_proto_chat_v1_chat_proto_msgTypes[13].OneofWrappers = []any{
		(*StreamMessageRequest_SendMessage)(nil),
		(*StreamMessageRequest_Heartbeat)(nil),
	}
	file_proto_chat_v1_chat_proto_msgTypes[14].OneofWrappers = []any{
		(*StreamMessageResponse_MessageReceived)(nil),
		(*StreamMessageResponse_PresenceEvent)(nil),
		(*StreamMessageResponse_ChannelJoined)(nil),
		(*StreamMessageResponse_ParticipantAdded)(nil),
		(*StreamMessageResponse_Error)(nil),
		(*StreamMessageResponse_IdentityEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chat_v1_chat_proto_rawDesc), len(file_proto_chat_v1_chat_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_v1_chat_proto_depIdxs,
		EnumInfos:         file_proto_chat_v1_chat_proto_enumTypes,
		MessageInfos:      file_proto_chat_v1_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_v1_chat_proto = out.File
	file_proto_chat_v1_chat_proto_goTypes = nil
	file_proto_chat_v1_chat_proto_depIdxs = nil
}
