package ui

import (
	"context"
	"fmt"
	"strings"

	tea "github.com/charmbracelet/bubbletea"
	chatv1 "go-simple-chat/api/v1"
	"go-simple-chat/cmd/client/model"
)

// HandleCommand parses and executes a command starting with /.
func HandleCommand(m ChatScreen, input string) tea.Cmd {
	parts := strings.Fields(input)
	if len(parts) == 0 {
		return nil
	}

	command := parts[0]
	args := parts[1:]

	switch command {
	case "/create":
		// Usage: /create <name> <user1> <user2>...
		if len(args) < 2 {
			return errorCmd(fmt.Errorf("usage: /create <group_name> <usernames...>"))
		}
		name := args[0]
		usernames := args[1:]
		return m.createChannelCmd(name, chatv1.CreateChannelRequest_TYPE_GROUP, usernames)

	case "/dm":
		// Usage: /dm <username>
		if len(args) < 1 {
			return errorCmd(fmt.Errorf("usage: /dm <username>"))
		}
		username := args[0]
		// For DMs, name is usually ignored or generated by the server/client later
		return m.createChannelCmd("", chatv1.CreateChannelRequest_TYPE_DIRECT, []string{username})

	case "/add":
		// Usage: /add <user1> <user2>...
		if len(args) < 1 {
			return errorCmd(fmt.Errorf("usage: /add <usernames...>"))
		}
		if m.activeChannelID == "" {
			return errorCmd(fmt.Errorf("no active channel"))
		}
		return m.addParticipantsCmd(m.activeChannelID, args)

	case "/presence":
		// Usage: /presence <username>
		if len(args) < 1 {
			return errorCmd(fmt.Errorf("usage: /presence <username>"))
		}
		return m.checkPresenceCmd(args[0])

	case "/read":
		// Usage: /read
		if m.activeChannelID == "" {
			return errorCmd(fmt.Errorf("no active channel"))
		}
		return m.markAsReadCmd(m.activeChannelID, "")

	case "/help":
		return errorCmd(fmt.Errorf("commands: /create <name> <users>, /dm <user>, /add <users>, /presence <user>, /read"))

	default:
		return errorCmd(fmt.Errorf("unknown command: %s", command))
	}
}

func errorCmd(err error) tea.Cmd {
	return func() tea.Msg {
		return model.MsgError{Err: err}
	}
}

// Extension methods for ChatScreen to support commands

func (m ChatScreen) createChannelCmd(name string, typ chatv1.CreateChannelRequest_Type, usernames []string) tea.Cmd {
	return func() tea.Msg {
		_, err := m.client.CreateChannel(context.Background(), &chatv1.CreateChannelRequest{
			Name:                 name,
			Type:                 typ,
			ParticipantUsernames: usernames,
		})
		if err != nil {
			return model.MsgError{Err: err}
		}
		// Success - trigger a reload of the channel list
		return m.loadChannelsCmd()()
	}
}

func (m ChatScreen) addParticipantsCmd(channelID string, usernames []string) tea.Cmd {
	return func() tea.Msg {
		_, err := m.client.AddParticipant(context.Background(), &chatv1.AddParticipantRequest{
			ChannelId: channelID,
			Usernames: usernames,
		})
		if err != nil {
			return model.MsgError{Err: err}
		}
		return nil
	}
}

func (m ChatScreen) checkPresenceCmd(username string) tea.Cmd {
	return func() tea.Msg {
		res, err := m.client.GetPresence(context.Background(), &chatv1.GetPresenceRequest{
			Usernames: []string{username},
		})
		if err != nil {
			return model.MsgError{Err: err}
		}
		if len(res.Presences) == 0 {
			return model.MsgError{Err: fmt.Errorf("User %s not found or presence unavailable", username)}
		}
		p := res.Presences[0]
		lastSeen := "never"
		if p.LastSeen != nil {
			lastSeen = p.LastSeen.AsTime().Format("2006-01-02 15:04:05")
		}
		status := "Offline"
		if p.Online {
			status = "Online"
		}
		return model.MsgError{Err: fmt.Errorf("User %s: %s (Last seen: %s)", p.Username, status, lastSeen)}
	}
}
